---
title: "Kodutöö"
output: 
  html_document:
    theme: null
---

# I osa

(**21 punkti**) Lahenda praktikumis alustatud [andmete veebist kraapimise](../praktikum5_web) ülesanded.

# II osa

Järgmises praktikumis kasutame peakomponentanalüüsi, seetõttu seisneb kodutöö II osa peakomponentanalüüsiga tutvumises. 

(**2 punkti**) Vaata videot [PCA 1: curse of dimensionality](https://www.youtube.com/watch?v=IbE0tbjy6JQ) 

* Selgita, mida tähendab, et andmestiku tegelik dimensionaalsus võib olla väiksem kui tunnuste arv andmestikus. Too kaks näidet. 

(**1 punkt**) Vaata videot [PCA 3: direction of greatest variance](https://www.youtube.com/watch?v=2bV_YQTIJrg) 

* Kuidas valitakse esimese peakomponendi suund (st millise kriteeriumi järgi valitakse esimene peakomponent)?

(**1 punkt**) Vaata Stanfordi masinõppe kursuse videot [Principal Component Analysis Problem Formulation](https://www.youtube.com/watch?v=T-B8muDvzu0)

* Mida uut said siit videost teada lisaks eelnevale kahele? Kumb meeldis rohkem? 

Lisaks võid uurida [Explained Visually: Principal Component Analysis](http://setosa.io/ev/principal-component-analysis/)

<!--

# Projekti teema otsimine (**5 boonuspunkti**)

Mõtle välja enda projekti teema ja postita see [Moodle's projekti foorumisse](https://moodle.ut.ee/mod/forum/view.php?id=664413). Kirjuta lühike ülevaade, milles projekt seisneb, kust andmed saad jne. Too välja ka kaasüliõpilaste nimed kellega koos projekti teete. Projekti juhendi leiad [siit](../projekt_juhend/). See "boonusülesanne" jääb üles projekti teemade fikseerimise tähtajani (vt. Moodle'st või projekti juhendist).

-->

# Mida on vaja esitada?

* I ja II osa kohta tuleb esitada vastustega [Jupyter fail](../kodutood/kodutoo5.ipynb).


Lahendused esitada [Moodle keskkonna](https://moodle.ut.ee/course/view.php?id=8013#section-1) kaudu.
