---
title: "Kodutöö"
output: 
  html_document:
    theme: null
---


# I osa - veebiloengud, videod, artiklid (4 punkti)
1. (**3 punkti**) Vaata Johns Hopkinsi andmeanalüüsi kursuse videosid:

* [The ggplot2 Plotting System - Part 2 (1/3)](https://www.youtube.com/watch?v=zLwrYvH2Hg0&list=PLjTlxb-wKvXPhZ7tQwlROtFjorSj9tUyZ&index=13)
* [The ggplot2 Plotting System - Part 2 (2/3)](https://www.youtube.com/watch?v=Z3WP_Up8b5I&list=PLjTlxb-wKvXPhZ7tQwlROtFjorSj9tUyZ&index=14)
* [The ggplot2 Plotting System - Part 2 (3/3)](https://www.youtube.com/watch?v=gU8w0gjSx40&list=PLjTlxb-wKvXPhZ7tQwlROtFjorSj9tUyZ&index=15)

Nimeta kolm kasulikku teadmist, mis videotest teada said. Juhul kui sa kõike juba teadsid, siis nimeta kolm sellist videos mainitud teadmist, mida sa kõige sagedamini kasutad.

2. (**1 punkt**) Vaata https://www.youtube.com/watch?v=5Dnw46eC-0o

Võta selle video idee ühe lausega kokku.

# II osa (10 punkti)

Lahenda praktikumis alustatud [*Growth in a Time of Debt*](../praktikum2_riigivolg) ülesanded.

# III osa (11 punkti)

Lahenda [pettuse tuvastamise ülesanded](../praktikum2_pettus). 

# Mida on vaja esitada?

* I, II ja III osa kohta tuleb esitada [Jupyter Notebook fail](../kodutood/kodutoo2.ipynb).

Lahendused esitada [Moodle keskkonna](https://moodle.ut.ee/course/view.php?id=8013#section-1) kaudu.

